config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get "/profile", to: 'pages#profile'
  # get "/user", to: 'pages#user'


  get "/matches", to: "matches#index"
  resources :flats, only: [:index, :new, :show, :create] do
    resources :viewings,  only: [:create]
  end

  resources :users, only: [:index, :show, :edit, :update]  do
    resources :flats, only: [:show]
  end

  resources :matches, only: [:show]

  resources :chats, only: [:index]

end

app/models/viewing.rb
class Viewing < ApplicationRecord

  belongs_to :user
  belongs_to :flat
  validates :user, uniqueness: { scope: :flat }

  after_save :check_matching, if: :like?

  def matched?
    check_matching == 1
  end

  private

  def check_matching
    MatcherService.check(self)
  end
end

app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  def create
    @viewing = Viewing.new(viewing_params)
    @flat = Flat.find(params[:flat_id])
    @viewing.flat = @flat
    @viewing.user = current_user
    if @viewing.save
      matched = @viewing.matched?
      @match = Match.last
      @flats = Flat.flat_query(current_user)
      render json: { matched: matched, flats: @flats }
    else
      @flats = Flat.flat_query(current_user)
      redirect_to flats_path, alert: "issue with this Match"
    end
  end

  def viewing_params
    params.require(:viewing).permit(:user, :like)
  end
end

app/views/viewings/_flats_list.html.erb
<div class="uk-card uk-card-default uk-width-1-2@m uk-box-shadow-small flat_card flat-box uk-border-rounded <%= 'active' if index == 0 %>" data-flat-id='<%= flat.id %>'>
    <div class="uk-card-media-top uk-border-rounded">
      <!-- <img data-src="https://images.unsplash.com/photo-1470619681920-17fd5fd2f094?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" width="400" height="500" alt="" class="uk-border-rounded" uk-img > -->

      <%= cl_image_tag(flat.photos.first.photo, :width=>400, :height=>350, :crop=>"fill")%>

    </div>
    <div>
      <h4 class="uk-margin-small-left uk-margin-top uk-margin-remove-bottom uk-card-title uk-text-bold"><%= flat.title %></h4>
      <p class="uk-margin-small-left uk-text-small uk-margin-remove-top uk-card-title"><span uk-icon="location"></span><%= flat.address %></p>
      <hr>
    </div>
     <div class="uk-card-body uk-flex uk-padding-remove-top justify-content-center align">
          <p class="uk-margin-remove mr-2 lead"><i class="fas fa-euro-sign fa-lg mx-2"></i><%= flat.rent %></p>
          <p class="uk-margin-remove mr-2 lead"><i class="fas fa-home fa-lg mx-2"></i><%= flat.square_meter%> sm</p>
          <p class= "uk-margin-remove mr-2 lead"><i class="fas fa-bed fa-lg mx-2"></i><%= flat.bedroom + 1 %></p>

     </div>
     <div class="uk-card-footer uk-padding-remove-horizontal">
       <div class ="uk-container uk-flex uk-flex-center">
       <%= link_to flat_viewings_path(flat, viewing: {like: false}), method: :post, remote: true, id: "reject-btn", class: "uk-button uk-button-danger uk-button-large like-btn uk-border-pill ", "data-flat-id" => flat.id  do %>
           <span  uk-icon="icon: close; ratio: 2"></span>
       <% end %>
         <%= link_to flat_path(flat), id: "info-btn", class: "uk-button uk-button-default uk-button-large like-btn uk-border-pill" do %>
             <span uk-icon="icon: info; ratio: 2"></span>
         <% end %>
       <%= link_to flat_viewings_path(flat, viewing: {like: true}), method: :post, remote: true, id: "sweet-alert-demo", id: "accept-btn" ,class: "uk-button uk-button-danger uk-button-large like-btn uk-border-pill", "data-flat-id" => flat.id   do %>
           <span uk-icon="icon: heart; ratio: 2"></span>
       <% end %>
      </div>
       <div class="uk-card-footer uk-margin-top">
      </div>
   </div>
 </div>

        <!-- TOP CONTAINER -->

app/views/viewings/_like.html.erb
<div class="uk-card uk-card-default uk-width-1-2@m uk-box-shadow-small flat-box <%= 'active' if index == 0 %>">
    <div class="uk-card-media-top uk-border-rounded">
      <img data-src="https://images.unsplash.com/photo-1470619681920-17fd5fd2f094?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" width="400" height="500" alt="" class="uk-border-rounded" uk-img >
    </div>
    <div>
      <h4 class="uk-margin-small-left uk-card-title uk-margin-top uk-margin-remove-bottom"><%= flat.title %></h4>
      <p class="uk-margin-small-left uk-text-small uk-margin-remove-top"><span uk-icon="location"></span><%= flat.address %></p>
         <%= link_to flat_path(flat), class: "uk-margin-small-left" do %>
             <span uk-icon="more"></span> More Information
         <% end %>
      <hr>
    </div>
     <div class="uk-card-body uk-flex uk-padding-remove-vertical ">
          <p class="uk-margin-remove mr-2"><i class="fas fa-euro-sign mx-2"></i><%= flat.rent %></p>
          <p class="uk-margin-remove mr-2"><i class="fas fa-home mx-2"></i><%= flat.square_meter %></p>
          <p class="uk-margin-remove mr-2"><i class="fas fa-ticket-alt mx-2"></i><%= flat.vacant_from %></p>
          <p class= "uk-margin-remove mr-2"><i class="fas fa-door-open mx-2"></i><%= flat.bedroom + 1 %></p>
     </div>
     <div class="uk-card-footer uk-flex uk-flex-center">
       <%= link_to flat_viewings_path(flat, viewing: {like: false}), method: :post, remote: true, class: "uk-button uk-button-danger uk-button-large like-btn", "data-flat-id" => flat.id  do %>
           <span uk-icon="close"></span>
       <% end %>
       <%= link_to flat_viewings_path(flat, viewing: {like: true}), method: :post, remote: true, class: "uk-button uk-button-primary uk-button-large like-btn", "data-flat-id" => flat.id  do %>
           <span uk-icon="check"></span>
       <% end %>
      </div>
      <div class="uk-card-footer">
     </div>
 </div>

app/views/viewings/create.js.erb
// function refreshFlatList(innerHTML) {
//   const newFlatList = document.getElementById('flats_partial_show');
//   newFlatList.innerHTML = "";
//   newFlatList.innerHTML = innerHTML;
// }


//   refreshFlatList('<%#= j render "viewings/flats_list", flats: @flats %>');













/*if @viewing.matched?

      redirect_to flats_path, notice: "you have a match!"

      else
         redirect_to flats_path
  end*/

app/views/viewings/new.html.erb
<h1>Viewings#new</h1>
<p>Find me in app/views/viewings/new.html.erb</p>