config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get "/profile", to: 'pages#profile'
  # get "/user", to: 'pages#user'


  get "/matches", to: "matches#index"
  resources :flats, only: [:index, :new, :show, :create] do
    resources :viewings,  only: [:create]
  end

  resources :users, only: [:index, :show, :edit, :update]  do
    resources :flats, only: [:show]
  end

  resources :matches, only: [:show]

  resources :chats, only: [:index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav" data-uk-sticky="cls-active: uk-background-default uk-box-shadow-medium; top: 100vh; animation: uk-animation-slide-top">
  <div class="uk-container">
    <nav class="uk-navbar uk-navbar-container uk-navbar-transparent" data-uk-navbar>
      <div class="uk-navbar-left">
        <div class="uk-navbar-item uk-padding-remove-horizontal">
           <a href="/"><%= image_tag("flinder.png", size: "60x15",class: "uk-logo") %>
        </div>
      </div>
      <div class="uk-navbar-left">
      </div>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav uk-visible@s">
          <li class="uk-active uk-visible@m"><a href="" data-uk-icon="home"></a></li>
            <a href="#" data-uk-icon="chevron-down">Products</a>
            <div class="uk-navbar-dropdown">
              <ul class="uk-nav uk-navbar-dropdown-nav">
                <li><%= link_to "Home", root_path%></li>
                <li><%= link_to "Your matches", matches_path%></li>
                <li><%= link_to "Find new home", flats_path%></li>
                <li><%= link_to "Add current home", new_flat_path%></li>
                <li><%= link_to "Profile / preferences", edit_user_registration_path(current_user)%></li>
                <li> <%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
                <li><%= link_to "Login", new_user_session_path%></li>
              </ul>
            </div>
        </ul>
        <a class="uk-navbar-toggle uk-navbar-item uk-hidden@s" data-uk-toggle data-uk-navbar-toggle-icon href="#offcanvas-nav"></a>
      </div>
    </nav>
  </div>
</div>

<div id="offcanvas-nav" data-uk-offcanvas="flip: true; overlay: false">
  <div class="uk-offcanvas-bar uk-offcanvas-bar-animation uk-offcanvas-slide">
    <button class="uk-offcanvas-close uk-close uk-icon" type="button" data-uk-close></button>
    <div class="uk-flex-top">
      <% if current_user  %>
      <h4 id="banner-name">Hello <%= current_user.first_name %></h4>
      <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src= "<%= current_user && cl_image_path(current_user.profile_photo) %>" />
      <% end  %>
    </div>
    <hr>
    <ul class="uk-nav uk-nav-default uk-margin-top">
      <li><%= link_to matches_path, class: "nav-font" do %>
            <span uk-icon="heart"></span> My matches
        <% end %></li>
        <% if user_signed_in? %>
      <li><%= link_to user_path(current_user), class: "nav-font" do %>
            <span uk-icon="search"></span> Find new home
        <% end %></li>
        <% end %>
      <li><%= link_to new_flat_path, class: "nav-font" do %>
           <span uk-icon="plus-circle"></span> My home
       <% end %></li>
      <li><%= link_to edit_user_registration_path(@user), class: "nav-font" do %>
            <span uk-icon="user"></span> My profile & preferences
        <% end %></li>
        <hr>
      <% if current_user.nil? %>
      <li><%= link_to new_user_session_path, class: "nav-font" do %>
            <span uk-icon="sign-in"></span> Sign-in
        <% end %></li>
        <% end %>
        <% if user_signed_in? %>
      <li><%= link_to destroy_user_session_path, method: :delete, class: "nav-font" do %>
            <span uk-icon="sign-out"></span> Sign-out
        <% end %></li>
        <% end %>
    </ul>
  </div>
</div>