config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  get "/profile", to: 'pages#profile'
  # get "/user", to: 'pages#user'


  get "/matches", to: "matches#index"
  resources :flats, only: [:index, :new, :show, :create] do
    resources :viewings,  only: [:create]
  end

  resources :users, only: [:index, :show, :edit, :update]  do
    resources :flats, only: [:show]
  end

  resources :matches, only: [:show]

  resources :chats, only: [:index]

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :asker, class_name: 'Flat'
  belongs_to :receiver, class_name: 'Flat'

  validates :asker, uniqueness: { scope: :receiver }

  def other_party(flat)
    if flat == asker
      return receiver
    elsif flat == receiver
      return asker
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = current_user.flat.all_matches.sort_by { |match| match.id }.reverse
    @photos = Photo.all
    #raise
    #@photos = Photo.where(flat_id: @matches.flat_id)
  end

  def show
    @match = Match.find(params[:id])
    @flat = @match.other_party(current_user.flat)
  end
end

app/views/matches/index.html.erb
<div class="uk-container">
<h4 class="uk-text-bold uk-text-center">Your Matches</h4>
  <% @matches.each do |match| %>
  <div>
    <div class="uk-child-width-1-2@s">
        <% flat = match.other_party(current_user.flat) %>
        <div class="uk-card uk-card-default uk-card-small uk-card-body">
          <h5 class="uk-card uk-text-bold uk-text-center"><%= flat.title %></h5>
          <div><%= cl_image_tag flat.photos.first.photo, height: 300, width: 400, crop: :fill%></div>
          <div class="uk-card-body uk-flex justify-content-center align">
          <p class="uk-margin-remove mr-2 lead"><i class="fas fa-euro-sign fa-lg mx-2"></i><%= flat.rent %></p>
          <p class="uk-margin-remove mr-2 lead"><i class="fas fa-home fa-lg mx-2"></i><%= flat.square_meter%> sm</p>
          <p class= "uk-margin-remove mr-2 lead"><i class="fas fa-bed fa-lg mx-2"></i><%= flat.bedroom + 1 %></p>

     </div>
          <%= link_to "Send a message", chats_path(), class: "uk-button uk-button-danger uk-width-1-1 uk-margin-small-top uk-border-pill uk-text-bold" %>
          <%= link_to "More details about person", match_path(match), class: "uk-button uk-button-primary uk-width-1-1 uk-margin-small-top uk-border-pill uk-text-bold" %>
        </div>
  </div>
  <br>
  </div>
  <% end %>
</div>

        <!-- TOP CONTAINER -->

app/views/matches/show.html.erb
<div class="uk-container">
<div class="uk-card uk-card-default uk-width-1-2@m">
  <%= link_to matches_path do %>
      <span uk-icon="chevron-left" class="uk-margin-remove"></span> Back
  <% end %>
    <div class="uk-card-header">
            <div class="uk-align-center">
                <%= cl_image_tag @flat.user.profile_photo,  class: "uk-align-center uk-border-pill", :width=>300, :height=>300, :crop=>"fill"%>
            </div>
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-expand">
            <h5 class="uk-card uk-text-center "><%= @flat.user.first_name %> <%= @flat.user.last_name %></h5>
               <hr class="uk-divider-icon">
               <dl class="uk-description-list">
                 <dt>Who I am</dt>
                 <dd><%= @flat.user.profile_description %></dd>
               </dl>
            </div>
        </div>
    </div class="uk-margin-bottom">
    <%= link_to "Send a message", chats_path(), class: "uk-button uk-button-danger uk-width-1-1 uk-margin-small-top uk-border-pill uk-text-bold" %>
    </div>
</div>
</div>

        <!-- TOP CONTAINER -->